// Auto-generated by scripts/generate-theme-registry.js. Do not edit.

import React from "react"

import StoreLayout from './store/Layout'
import StoreHeader from './store/Header'
import StoreFooter from './store/Footer'
import WebsiteLayout from './website/Layout'
import WebsiteHeader from './website/Header'
import WebsiteFooter from './website/Footer'
import StoreHome from './store/Home'
import WebsiteHome from './website/Home'

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type ThemeShell = { Layout: React.ComponentType<any>; Header: React.ComponentType<any>; Footer: React.ComponentType<any> }

export interface ThemeHomeProps {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  pageData: any | null
  locale: string
}

export const THEME_REGISTRY: Record<string, ThemeShell> = {
  store: { Layout: StoreLayout, Header: StoreHeader, Footer: StoreFooter },
  website: { Layout: WebsiteLayout, Header: WebsiteHeader, Footer: WebsiteFooter },
}

export const HOME_REGISTRY: Record<string, React.ComponentType<ThemeHomeProps> | null> = {
  store: StoreHome,
  website: WebsiteHome,
}
